### ISSUE TITLE
Accelerated JAX on Apple silicon

### ISSUE THREAD

**Issue by Marius1311** [ott-jax/ott#402] opened 2023-07-28 08:33 UTC
Hi OTT team, it looks like JAX can now take advantage of hardware acceleration on Apple silicon architectures, see https://developer.apple.com/metal/jax/. Would it be possible to make use of this in ott-jax? I naively followed their installation instructions and managed to install JAX with the metal backend, however, anytime I then tried calling a solver in ott-jax, my kernel died, so that does not seem to work yet.

**Comment by michalk8** [comment] 2023-08-01 16:32
I tried running the [Getting Started](https://ott-jax.readthedocs.io/en/latest/tutorials/notebooks/basic_ot_between_datasets.html) and was successful. However, running [Low-rank Sinkhorn](https://ott-jax.readthedocs.io/en/latest/tutorials/notebooks/LRSinkhorn.html) failed.

The problem is that it it's still highly experimental, e.g. `jnp.where(jnp.ones((2,)) > 0.0)
` this crashes for me (`jnp.where(jnp.ones((2,)) > 0.0, True, False)` is fine though):

<details>

```
"builtin.module"() ({
  "func.func"() ({
  ^bb0(%arg0: tensor<2xi1>):
    %0 = "mhlo.constant"() {value = dense<0> : tensor<i32>} : () -> tensor<si32>
    %1 = "mhlo.convert"(%arg0) : (tensor<2xi1>) -> tensor<2xsi32>
    %2 = "mhlo.slice"(%1) {limit_indices = dense<1> : tensor<1xi64>, start_indices = dense<0> : tensor<1xi64>, strides = dense<2> : tensor<1xi64>} : (tensor<2xsi32>) -> tensor<1xsi32>
    %3 = "mhlo.slice"(%1) {limit_indices = dense<2> : tensor<1xi64>, start_indices = dense<1> : tensor<1xi64>, strides = dense<2> : tensor<1xi64>} : (tensor<2xsi32>) -> tensor<1xsi32>
    %4 = "mhlo.add"(%2, %3) : (tensor<1xsi32>, tensor<1xsi32>) -> tensor<1xsi32>
    %5 = "mhlo.slice"(%1) {limit_indices = dense<1> : tensor<1xi64>, start_indices = dense<0> : tensor<1xi64>, strides = dense<1> : tensor<1xi64>} : (tensor<2xsi32>) -> tensor<1xsi32>
    %6 = "mhlo.pad"(%5, %0) {edge_padding_high = dense<1> : tensor<1xi64>, edge_padding_low = dense<0> : tensor<1xi64>, interior_padding = dense<1> : tensor<1xi64>} : (tensor<1xsi32>, tensor<si32>) -> tensor<2xsi32>
    %7 = "mhlo.pad"(%4, %0) {edge_padding_high = dense<0> : tensor<1xi64>, edge_padding_low = dense<1> : tensor<1xi64>, interior_padding = dense<1> : tensor<1xi64>} : (tensor<1xsi32>, tensor<si32>) -> tensor<2xsi32>
    %8 = "mhlo.add"(%6, %7) : (tensor<2xsi32>, tensor<2xsi32>) -> tensor<2xsi32>
    "func.return"(%8) : (tensor<2xsi32>) -> ()
  }) {arg_attrs = [{jax.arg_info = "a", mhlo.sharding = "{replicated}"}], function_type = (tensor<2xi1>) -> tensor<2xi32>, res_attrs = [{jax.result_info = ""}], sym_name = "main", sym_visibility = "public"} : () -> ()
}) {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32, sym_name = "jit__cumulative_reduction"} : () -> ()
```

```pytb
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
Cell In[23], line 1
----> 1 jnp.where(jnp.ones((2,)) > 0.0)

File ~/.mambaforge/envs/ott-metal/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py:1091, in where(condition, x, y, size, fill_value)
   1089 if x is None and y is None:
   1090   util.check_arraylike("where", condition)
-> 1091   return nonzero(condition, size=size, fill_value=fill_value)
   1092 else:
   1093   util.check_arraylike("where", condition, x, y)

File ~/.mambaforge/envs/ott-metal/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py:1363, in nonzero(***failed resolving arguments***)
   1361 if arr.size == 0 or size == 0:
   1362   return tuple(zeros(size, int) for dim in arr.shape)
-> 1363 flat_indices = reductions.cumsum(bincount(reductions.cumsum(mask), length=size))
   1364 strides = (np.cumprod(arr.shape[::-1])[::-1] // arr.shape).astype(int_)
   1365 out = tuple((flat_indices // stride) % size for stride, size in zip(strides, arr.shape))

File ~/.mambaforge/envs/ott-metal/lib/python3.10/site-packages/jax/_src/numpy/reductions.py:651, in _make_cumulative_reduction.<locals>.cumulative_reduction(a, axis, dtype, out)
    648 @_wraps(np_reduction, skip_params=['out'])
    649 def cumulative_reduction(a: ArrayLike, axis: Axis = None,
    650                          dtype: DTypeLike = None, out: None = None) -> Array:
--> 651   return _cumulative_reduction(a, _ensure_optional_axes(axis), dtype, out)

    [... skipping hidden 14 frame]

File ~/.mambaforge/envs/ott-metal/lib/python3.10/site-packages/jax/_src/dispatch.py:465, in backend_compile(backend, module, options, host_callbacks)
    460   return backend.compile(built_c, compile_options=options,
    461                          host_callbacks=host_callbacks)
    462 # Some backends don't have `host_callbacks` option yet
    463 # TODO(sharadmv): remove this fallback when all backends allow `compile`
    464 # to take in `host_callbacks`
--> 465 return backend.compile(built_c, compile_options=options)

XlaRuntimeError: UNKNOWN: /var/folders/pm/3h0fxf7n5r17nz_7gllk0pdw0000gn/T/ipykernel_86432/7272384.py:1:0: error: failed to legalize operation 'mhlo.pad'
/var/folders/pm/3h0fxf7n5r17nz_7gllk0pdw0000gn/T/ipykernel_86432/7272384.py:1:0: note: called from
/var/folders/pm/3h0fxf7n5r17nz_7gllk0pdw0000gn/T/ipykernel_86432/7272384.py:1:0: note: see current operation: %21 = "mhlo.pad"(%20, %1) {edge_padding_high = dense<1> : tensor<1xi64>, edge_padding_low = dense<0> : tensor<1xi64>, interior_padding = dense<1> : tensor<1xi64>} : (tensor<1xsi32>, tensor<si32>) -> tensor<2xsi32>
```

</details>

Since it's not stable ATM, we will need to wait to test metal; closing this for now.

**Closed by michalk8** 2023-08-01 16:32 UTC
Labels: question
